server:
  port: 8080
liteflow:
  print-banner: false
jimmer:
  language: kotlin
compose:
  oss:
    provider: minio
spring:
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off
  flyway:
    enabled: true
    baseline-version: 3000
    baseline-on-migrate: true
    out-of-order: true
  threads:
    virtual:
      enabled: true
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  data:
    redis:
      repositories:
        enabled: false # 关闭仓库扫描
      client-type: lettuce
management:
  health:
    redis:
      enabled: true
