server:
  port: 8080
compose:
  psdk:
    wxpa:
      wxpa:
        verifyToken: ${WXPA_VERIFY_TOKEN}
        appId: ${WXPA_APP_ID}
        appSecret: ${WXPA_APP_SECRET}
  oss:
    provider: minio
    endpoint: ${GLOBAL_DOMAIN}
    exposed-base-url: http://${GLOBAL_DOMAIN}:9000
    minio:
      port: ${MINIO_PORT:9000}
      secret-key: ${MINIO_PASSWORD:minio123}
      access-key: ${MINIO_USER:minio}
      enable-ssl: false

spring:
  docker:
    compose:
      enabled: false
      file: classpath:compose.yaml
  data:
    redis:
      password: redis123
      host: 127.0.0.1
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${GLOBAL_IP}:${PG_PORT}/${PG_DB}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
jimmer:
  show-sql: true
  pretty-sql: true
  inline-sql-variables: true
  client:
    ts:
      path: /ts.zip
      indent: 2
      mutable: true
      is-enum-ts-style: false
    openapi:
      path: /jimmer.yaml
      ui-path: /jimmer.html
      properties:
        info:
          title: My Web Service
          description: |
            Restore the DTO explosion that was 
            eliminated by server-side developers
          version: 1.0
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
sa-token:
  is-log: true
  is-color-log: true
  log-level: TRACE
logging:
  config: classpath:logback-dev.xml
  level:
    root: error
    org.babyfish.jimmer: info
    io.github.truenine: trace
    com.tnmaster: trace
