server:
  port: 8080
compose:
  psdk:
    wxpa:
      wxpa:
        verify-token: ${WXPA_VERIFY_TOKEN}
        app-id: ${WXPA_APP_ID}
        app-secret: ${WXPA_APP_SECRET}
  oss:
    provider: minio
    endpoint: ${GLOBAL_DOMAIN}
    exposed-base-url: http://${GLOBAL_DOMAIN}:9000
    minio:
      port: ${MINIO_PORT}
      secret-key: ${MINIO_PASSWORD}
      access-key: ${MINIO_USER}
      enable-ssl: false

spring:
  docker:
    compose:
      enabled: true
      file: classpath:compose.yaml
      lifecycle-management: start_and_stop
  data:
    redis:
      password: ${REDIS_PASSWORD}
      host: ${GLOBAL_IP}
      port: ${REDIS_PORT}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${GLOBAL_IP}:${PG_PORT}/${PG_DB}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
jimmer:
  show-sql: true
  pretty-sql: true
  inline-sql-variables: true
  client:
    ts:
      path: /ts.zip
      indent: 2
      mutable: true
      is-enum-ts-style: false
    openapi:
      path: /jimmer.yaml
      ui-path: /jimmer.html
      properties:
        info:
          title: My Web Service
          description: |
            Restore the DTO explosion that was 
            eliminated by server-side developers
          version: 1.0
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
logging:
  config: classpath:logback-dev.xml
  level:
    root: info
    org.babyfish.jimmer: info
    io.github.truenine: trace
    com.tnmaster: trace
