server:
  port: 8080
compose:
  psdk:
    wxpa:
      wxpa:
        verify-token: ${WXPA_VERIFY_TOKEN}
        app-id: ${WXPA_APP_ID}
        app-secret: ${WXPA_APP_SECRET}
  oss:
    provider: minio
    endpoint: localhost
    exposed-base-url: http://localhost:9000
    minio:
      port: 9000
      secret-key: minio123
      access-key: minio
      enable-ssl: false

spring:
  docker:
    compose:
      enabled: true
      file: classpath:compose.yaml
      lifecycle-management: start_and_stop
  data:
    redis:
      password: redis123
      host: 127.0.0.1
      port: 6379
      connect-timeout: 3s
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/maliang
    username: postgres
    password: postgres
jimmer:
  show-sql: true
  pretty-sql: true
  inline-sql-variables: true
  client:
    ts:
      path: /ts.zip
      indent: 2
      mutable: true
      is-enum-ts-style: false
    openapi:
      path: /jimmer.yaml
      ui-path: /jimmer.html
      properties:
        info:
          title: My Web Service
          description: |
            Restore the DTO explosion that was 
            eliminated by server-side developers
          version: 1.0
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
logging:
  config: classpath:logback-dev.xml
  level:
    root: info
    org.babyfish.jimmer: info
    io.github.truenine: trace
    com.tnmaster: trace
